### ISSUE TITLE
Debian bookworm (12) builds are failing

### ISSUE THREAD

**Issue by dominykas** [cloudnative-pg/postgres-containers#109]
Debian bullseye (11) seems to still be the default for these containers, but it's approaching EOL date, if we are to believe https://wiki.debian.org/DebianReleases

Debian bookworm (12) containers haven't had a release in 2 weeks, possibly longer, given that e.g. the v15 release line for bullseye is at `15.7-5`, whereas the bookworm release line is at `15.7-1` (not sure if this carries any significance).

The `main` branch status checks seem to indicate that all bookworm builds are currently failing.

**Comment by sxd** [comment]
Hello @dominykas 

We're aware of it, but it's required sometimes to fix this issue since is due to a problem with the Barman build, we will keep this open until we fix it

Thanks for the heads up!

Regards!
