### ISSUE TITLE
Create images with PostGIS support

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/postgres-containers#13]
Based in our latest Developers Meeting, we agree on creating the PostGIS images since there's people asking about this.
The main idea it's to keep it as simple as possible using the community which already provide the proper support for PostGIS.

The images aren't supposed to support PostGIS upgrade process for now.

The plan is:
* Use the community PostGIS image from [here](https://hub.docker.com/r/postgis/postgis)
* Install Barman Cloud utilities

**Comment by sxd** [comment]
One possible issue here is that 12 13 and 14 are Debian based images, but, do we need to support 10 and 11? considering that 10 will lose support by the end of this year

**Comment by gbartolini** [comment]
After looking at the existing patch, I am more oriented towards creating a new repository called "postgis-containers" and keep them separated from the plain postgres ones.

**Comment by gbartolini** [comment]
I have created the postgis-containers repository @sxd @litaocdl

**Comment by litaocdl** [comment]
I am moving the postgis code into the new repository

**Comment by sxd** [comment]
Images are now in the new repo https://github.com/cloudnative-pg/postgis-containers in the main branch since it was the first commit

**Comment by litaocdl** [comment]
As it is in already main, I am going to test it

**Comment by litaocdl** [comment]
for postgis version, one postgres major version may have multiple postgis version, I think we all support postgis 3.2.2 for now.

**Comment by litaocdl** [comment]
@sxd May you also have a review for the pr as the init one is already in. Thanks
