### ISSUE TITLE
test pg15

### ISSUE THREAD

**Issue by akretschmeredb** [cloudnative-pg/postgres-containers#6]
Hi team,

it would be great to test PostgreSQL15 via k8s, but i can't find images.

**Comment by litaocdl** [comment]
The opensource postgres does not have container for version 15 yet, we will wait for that
https://hub.docker.com/_/postgres

**Comment by sxd** [comment]
@akretschmeredb if you want to push more on the community side of the postgres image, you can go and open an issue here https://github.com/docker-library/postgres
