### ISSUE TITLE
Support immutable versions

### ISSUE THREAD

**Issue by volschin** [cloudnative-pg/postgres-containers#98]
Pinning a specific version like http://ghcr.io/cloudnative-pg/postgresql:15.6-13 the contents of this manifest is changed every day.
Good practice is that I am able to pin a version, that is really immutable. This means for every build there should be a new increasing additional version like 15.6-13-625 where 625 could be the number of the workflow run.

**Comment by gbartolini** [comment]
Normally, you should use a digest to pin a specific immutable version of the image, as outlined here: https://cloudnative-pg.io/documentation/current/quickstart/#part-3-deploy-a-postgresql-cluster

Starting with 1.23 you have more flexibility with image catalogs.

Regarding details about building the images, I will defer this to @NiccoloFei. We should increase the image version when there are significant changes in the combination of packages and libraries included in the image, but I don't have the exact details.
